import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react";
import { Providers } from "./Providers";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "next auth login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <Providers>
          <div className="flex min-h-screen  container mx-auto">
            <Navbar />
            <main className="flex-1">{children}</main>
            <SpeedInsights />{" "}
          </div>
        </Providers>
      </body>
    </html>
  );
}
